export const FIXED_EDZESEK = [
  {
    id: "guggolas",
    nev: "Guggolás",
    leiras: "Alsótest erősítés, fókuszban a comb és a farizom.",
    kategoria: "Alsótest",
    munka_mp: 40,
    piheno_mp: 20,
    korok: 3,
    ismetles_szoveg: "",
    tipus: "idő alapú",
    nehezseg: "közepes",
    aktiv: true,
    sorrend: 1
  },
  {
    id: "fekvotamasz",
    nev: "Fekvőtámasz",
    leiras: "Mell, váll és tricepsz erősítése. Figyelj a stabil törzsre.",
    kategoria: "Felsőtest",
    munka_mp: 30,
    piheno_mp: 15,
    korok: 3,
    ismetles_szoveg: "",
    tipus: "idő alapú",
    nehezseg: "közepes",
    aktiv: true,
    sorrend: 2
  },
  {
    id: "plank",
    nev: "Plank",
    leiras: "Törzs stabilizálás és core erősítés. Egyenes testtartással tartsd.",
    kategoria: "Hasizom",
    munka_mp: 45,
    piheno_mp: 15,
    korok: 3,
    ismetles_szoveg: "",
    tipus: "idő alapú",
    nehezseg: "könnyű",
    aktiv: true,
    sorrend: 3
  },
  {
    id: "kitores",
    nev: "Kitörés",
    leiras: "Comb és farizom fejlesztése váltott lábbal, kontrollált mozgással.",
    kategoria: "Alsótest",
    munka_mp: 35,
    piheno_mp: 20,
    korok: 3,
    ismetles_szoveg: "",
    tipus: "idő alapú",
    nehezseg: "közepes",
    aktiv: true,
    sorrend: 4
  },
  {
    id: "mountain-climber",
    nev: "Hegymászó",
    leiras: "Állóképesség és core fejlesztése. Tartsd feszesen a törzsed.",
    kategoria: "Kardió",
    munka_mp: 30,
    piheno_mp: 15,
    korok: 3,
    ismetles_szoveg: "",
    tipus: "idő alapú",
    nehezseg: "közepes",
    aktiv: true,
    sorrend: 5
  },
  {
    id: "burpee",
    nev: "Burpee",
    leiras: "Teljes testes gyakorlat, magas pulzus és erős terhelés.",
    kategoria: "Teljes test",
    munka_mp: 40,
    piheno_mp: 20,
    korok: 3,
    ismetles_szoveg: "",
    tipus: "idő alapú",
    nehezseg: "nehéz",
    aktiv: true,
    sorrend: 6
  },
  {
    id: "csipoemeles",
    nev: "Csípőemelés",
    leiras: "Farizom aktiválás és alsótest stabilitás lassú emeléssel.",
    kategoria: "Farizom",
    munka_mp: 40,
    piheno_mp: 20,
    korok: 3,
    ismetles_szoveg: "",
    tipus: "idő alapú",
    nehezseg: "könnyű",
    aktiv: true,
    sorrend: 7
  },
  {
    id: "oldalemeles",
    nev: "Oldalemelés",
    leiras: "Váll izoláció. Kis súllyal, kontrollált mozgással végezd.",
    kategoria: "Váll",
    munka_mp: 35,
    piheno_mp: 15,
    korok: 3,
    ismetles_szoveg: "12 ismétlés",
    tipus: "ismétlés alapú",
    nehezseg: "közepes",
    aktiv: true,
    sorrend: 8
  },
  {
    id: "biciklis-haspres",
    nev: "Biciklis hasprés",
    leiras: "Ferde hasizmok és core aktiválás váltott mozdulatokkal.",
    kategoria: "Hasizom",
    munka_mp: 40,
    piheno_mp: 15,
    korok: 3,
    ismetles_szoveg: "",
    tipus: "idő alapú",
    nehezseg: "közepes",
    aktiv: true,
    sorrend: 9
  },
  {
    id: "jumping-jack",
    nev: "Jumping Jack",
    leiras: "Könnyű kardió és bemelegítés, pörgős mozgással.",
    kategoria: "Kardió",
    munka_mp: 30,
    piheno_mp: 10,
    korok: 3,
    ismetles_szoveg: "",
    tipus: "idő alapú",
    nehezseg: "könnyű",
    aktiv: true,
    sorrend: 10
  },
  {
    id: "labemeles-fekve",
    nev: "Lábemelés fekve",
    leiras: "Alsó has fókusz, lassú visszaengedéssel.",
    kategoria: "Hasizom",
    munka_mp: 35,
    piheno_mp: 15,
    korok: 3,
    ismetles_szoveg: "",
    tipus: "idő alapú",
    nehezseg: "közepes",
    aktiv: true,
    sorrend: 11
  },
  {
    id: "vadli-emeles",
    nev: "Vádli emelés",
    leiras: "Vádli erősítése teljes mozgástartománnyal.",
    kategoria: "Alsótest",
    munka_mp: 30,
    piheno_mp: 15,
    korok: 4,
    ismetles_szoveg: "15 ismétlés",
    tipus: "ismétlés alapú",
    nehezseg: "könnyű",
    aktiv: true,
    sorrend: 12
  },
  {
    id: "oldalso-terdemeles",
    nev: "Oldalsó térdemelés",
    leiras: "Core és csípő aktiválás lassú kivitelezéssel.",
    kategoria: "Core",
    munka_mp: 30,
    piheno_mp: 15,
    korok: 3,
    ismetles_szoveg: "",
    tipus: "idő alapú",
    nehezseg: "könnyű",
    aktiv: true,
    sorrend: 13
  },
  {
    id: "szek-tricepsz",
    nev: "Székes tricepsz",
    leiras: "Tricepsz erősítés székkel vagy paddal.",
    kategoria: "Kar",
    munka_mp: 30,
    piheno_mp: 20,
    korok: 3,
    ismetles_szoveg: "10 ismétlés",
    tipus: "ismétlés alapú",
    nehezseg: "közepes",
    aktiv: true,
    sorrend: 14
  },
  {
    id: "vallkorzes",
    nev: "Vállkörzés",
    leiras: "Bemelegítő vállmobilizáció.",
    kategoria: "Bemelegítés",
    munka_mp: 25,
    piheno_mp: 10,
    korok: 2,
    ismetles_szoveg: "",
    tipus: "idő alapú",
    nehezseg: "könnyű",
    aktiv: true,
    sorrend: 15
  
},
{
  id: "konnyu-ulesbol-felallas",
  nev: "Könnyű ülésből felállás",
  leiras: "Segít az alsótest erősítésében anélkül, hogy túlterhelné az ízületeket. Ülj le egy stabil székre, a talpak legyenek a talajon. Lassan állj fel, majd kontrolláltan ülj vissza. Használd a kezed segítségként, ha szükséges. Végezd nyugodt tempóban, fájdalom nélkül.",
  kategoria: "Kímélő erősítés",
  munka_mp: 30,
  piheno_mp: 30,
  korok: 2,
  ismetles_szoveg: "6-8 ismétlés",
  tipus: "idő alapú",
  nehezseg: "könnyű",
  aktiv: true,
  sorrend: 99
}
  
];
