export const FIXED_EXERCISES_HU = [
  {
    id: "guggolas",
    name: "Guggolás",
    desc: "Alsótest erősítés, fókuszban a comb és a farizom.",
    category: "Alsótest",
    workSec: 40,
    restSec: 20,
    rounds: 3,
    repsText: "",
    type: "nem-videós",
    difficulty: "közepes",
    active: true,
    sortOrder: 1
  },
  {
    id: "fekvotamasz",
    name: "Fekvőtámasz",
    desc: "Mell, váll és tricepsz erősítése. Figyelj a stabil törzsre.",
    category: "Felsőtest",
    workSec: 30,
    restSec: 15,
    rounds: 3,
    repsText: "",
    type: "nem-videós",
    difficulty: "közepes",
    active: true,
    sortOrder: 2
  },
  {
    id: "plank",
    name: "Plank",
    desc: "Törzs stabilizálás és core erősítés. Egyenes testtartással tartsd.",
    category: "Hasizom",
    workSec: 45,
    restSec: 15,
    rounds: 3,
    repsText: "",
    type: "nem-videós",
    difficulty: "könnyű",
    active: true,
    sortOrder: 3
  },
  {
    id: "kitores",
    name: "Kitörés",
    desc: "Comb és farizom fejlesztése, váltott lábbal, kontrollált mozgással.",
    category: "Alsótest",
    workSec: 35,
    restSec: 20,
    rounds: 3,
    repsText: "",
    type: "nem-videós",
    difficulty: "közepes",
    active: true,
    sortOrder: 4
  },
  {
    id: "mountain-climber",
    name: "Mountain Climber",
    desc: "Állóképesség és core. Tartsd feszesen a törzset gyors tempó mellett is.",
    category: "Kardió",
    workSec: 30,
    restSec: 15,
    rounds: 3,
    repsText: "",
    type: "nem-videós",
    difficulty: "közepes",
    active: true,
    sortOrder: 5
  },
  {
    id: "burpee",
    name: "Burpee",
    desc: "Teljes testes gyakorlat, magas pulzus és erős metabolikus terhelés.",
    category: "Teljes test",
    workSec: 40,
    restSec: 20,
    rounds: 3,
    repsText: "",
    type: "nem-videós",
    difficulty: "nehéz",
    active: true,
    sortOrder: 6
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    desc: "Farizom aktiválás és alsótest stabilitás. Lassú, kontrollált emeléssel.",
    category: "Farizom",
    workSec: 40,
    restSec: 20,
    rounds: 3,
    repsText: "",
    type: "nem-videós",
    difficulty: "könnyű",
    active: true,
    sortOrder: 7
  },
  {
    id: "oldalemeles",
    name: "Oldalemelés",
    desc: "Váll izoláció. Kis súllyal, kontrollált emeléssel dolgozz.",
    category: "Váll",
    workSec: 35,
    restSec: 15,
    rounds: 3,
    repsText: "12 ismétlés",
    type: "nem-videós",
    difficulty: "közepes",
    active: true,
    sortOrder: 8
  },
  {
    id: "bikiclis-haspres",
    name: "Biciklis hasprés",
    desc: "Ferde hasizmok és teljes core bekapcsolása váltott könyök-térd mozgással.",
    category: "Hasizom",
    workSec: 40,
    restSec: 15,
    rounds: 3,
    repsText: "",
    type: "nem-videós",
    difficulty: "közepes",
    active: true,
    sortOrder: 9
  },
  {
    id: "jumping-jack",
    name: "Jumping Jack",
    desc: "Bemelegítéshez vagy rövid kardió blokkhoz. Könnyű, pörgős mozgás.",
    category: "Kardió",
    workSec: 30,
    restSec: 10,
    rounds: 3,
    repsText: "",
    type: "nem-videós",
    difficulty: "könnyű",
    active: true,
    sortOrder: 10
  },
  {
    id: "labemeles-fekve",
    name: "Lábemelés fekve",
    desc: "Alsó has fókuszú gyakorlat, lassú visszaengedéssel.",
    category: "Hasizom",
    workSec: 35,
    restSec: 15,
    rounds: 3,
    repsText: "",
    type: "nem-videós",
    difficulty: "közepes",
    active: true,
    sortOrder: 11
  },
  {
    id: "vadli-emeles",
    name: "Vádli emelés",
    desc: "Vádli erősítése álló helyzetben, teljes mozgástartománnyal.",
    category: "Alsótest",
    workSec: 30,
    restSec: 15,
    rounds: 4,
    repsText: "15 ismétlés",
    type: "nem-videós",
    difficulty: "könnyű",
    active: true,
    sortOrder: 12
  },
  {
    id: "oldalso-terdemeles",
    name: "Oldalsó térdemelés",
    desc: "Oldalsó core és csípő aktiválás, lassú és kontrollált kivitelezéssel.",
    category: "Core",
    workSec: 30,
    restSec: 15,
    rounds: 3,
    repsText: "",
    type: "nem-videós",
    difficulty: "könnyű",
    active: true,
    sortOrder: 13
  },
  {
    id: "szek-tamaszos-tricepsz",
    name: "Szék támaszos tricepsz",
    desc: "Tricepsz erősítés otthoni környezetben, székkel vagy paddal.",
    category: "Kar",
    workSec: 30,
    restSec: 20,
    rounds: 3,
    repsText: "10 ismétlés",
    type: "nem-videós",
    difficulty: "közepes",
    active: true,
    sortOrder: 14
  },
  {
    id: "vall-korzes",
    name: "Vállkörzés",
    desc: "Bemelegítő vállmobilizáció, könnyű átmozgatás edzés elejére.",
    category: "Bemelegítés",
    workSec: 25,
    restSec: 10,
    rounds: 2,
    repsText: "",
    type: "nem-videós",
    difficulty: "könnyű",
    active: true,
    sortOrder: 15
  }
];
